### ISSUE TITLE
some problem with nolds.hurst_rs() i ran the function in a loop for 20 times with same data and it give me different values. I even done it with out the round() function still same problem

### ISSUE THREAD

**Issue by Krishnanunnis** [CSchoel/nolds#22] opened 2021-04-24 19:52 UTC
![image](https://user-images.githubusercontent.com/64976289/115971106-45207600-a564-11eb-9c16-0e303ba29fad.png)

**Comment by CSchoel** [comment] 2021-05-30 19:11
Hey, @Krishnanunnis . Sorry, I somehow completely missed this issue! :see_no_evil: 

The reason for this behavior is that `hurst_rs` uses the RANSAC algorithm for line fitting. This algorithm uses pseudorandom numbers to exclude outliers from the fitting procedure. If you use the keyword argument `fit="poly"` instead, the result should be perfectly deterministic.

I might consider reverting the default to `"poly"`, since you are the second person that ran into this issue and RANSAC is not part of the standard definition of the algorithm. But since this is only a question of defaults and not a bug, I will close the issue for now.

**Closed by CSchoel** 2021-05-30 19:11 UTC
